export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_FILE_LIST = 'UPDATE_FILE_LIST';
export const UPDATE_UPLOAD_CIRCLE = 'UPDATE_UPLOAD_CIRCLE';
export const UPDATE_FILE_ERR = 'UPDATE_FILE_ERR';
export const UPDATE_CURRENT_ADBOARD = 'UPDATE_CURRENT_ADBOARD';
export const TOGGLE_DASH_SIDE = 'TOGGLE_DASH_SIDE';
export const UPDATE_DASH_TAB = 'UPDATE_DASH_TAB';
export const UPDATE_PROJECT_TAB = 'UPDATE_PROJECT_TAB';
